"""
错误监控和告警系统
提供实时错误监控、告警触发和通知功能
"""

import os
import json
import time
import smtplib
import requests
from datetime import datetime, timedelta
from typing import Dict, Any, List, Optional, Callable, Union
from pathlib import Path
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dataclasses import dataclass, asdict
from enum import Enum

from .exceptions import StockInfoError, ErrorCode, ErrorSeverity
from .error_logger import ErrorLogger, error_logger
from .logger import get_logger

logger = get_logger(__name__)

# 告警级别枚举
class AlertLevel(Enum):
    """告警级别"""
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"
    EMERGENCY = "EMERGENCY"

# 告警状态枚举
class AlertStatus(Enum):
    """告警状态"""
    ACTIVE = "ACTIVE"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"
    SUPPRESSED = "SUPPRESSED"

@dataclass
class AlertRule:
    """告警规则"""
    name: str
    description: str
    condition: str  # 条件表达式
    threshold: Union[int, float]
    time_window: int  # 时间窗口（分钟）
    severity: AlertLevel
    enabled: bool = True
    cooldown_period: int = 60  # 冷却期（分钟）
    notification_channels: List[str] = None
    
    def __post_init__(self):
        if self.notification_channels is None:
            self.notification_channels = ['log']

@dataclass
class Alert:
    """告警信息"""
    id: str
    rule_name: str
    message: str
    severity: AlertLevel
    status: AlertStatus
    triggered_at: datetime
    acknowledged_at: Optional[datetime] = None
    resolved_at: Optional[datetime] = None
    context: Dict[str, Any] = None
    notification_sent: bool = False
    
    def to_dict(self) -> Dict[str, Any]:
        """转换为字典"""
        data = asdict(self)
        data['triggered_at'] = self.triggered_at.isoformat()
        if self.acknowledged_at:
            data['acknowledged_at'] = self.acknowledged_at.isoformat()
        if self.resolved_at:
            data['resolved_at'] = self.resolved_at.isoformat()
        data['severity'] = self.severity.value
        data['status'] = self.status.value
        return data

class NotificationChannel:
    """通知渠道基类"""
    
    def __init__(self, name: str, config: Dict[str, Any]):
        self.name = name
        self.config = config
        self.enabled = config.get('enabled', True)
    
    def send_notification(self, alert: Alert) -> bool:
        """发送通知"""
        raise NotImplementedError
    
    def test_connection(self) -> bool:
        """测试连接"""
        raise NotImplementedError

class EmailNotificationChannel(NotificationChannel):
    """邮件通知渠道"""
    
    def send_notification(self, alert: Alert) -> bool:
        """发送邮件通知"""
        try:
            if not self.enabled:
                return False
            
            smtp_server = self.config['smtp_server']
            smtp_port = self.config['smtp_port']
            username = self.config['username']
            password = self.config['password']
            from_addr = self.config['from_address']
            to_addrs = self.config['to_addresses']
            
            # 创建邮件
            msg = MIMEMultipart()
            msg['From'] = from_addr
            msg['To'] = ', '.join(to_addrs)
            msg['Subject'] = f"[{alert.severity.value}] StockInfoDownloader Alert: {alert.rule_name}"
            
            # 邮件内容
            body = f"""
Alert Details:
- Rule: {alert.rule_name}
- Severity: {alert.severity.value}
- Message: {alert.message}
- Triggered At: {alert.triggered_at.strftime('%Y-%m-%d %H:%M:%S')}
- Status: {alert.status.value}

Context:
{json.dumps(alert.context or {}, indent=2, ensure_ascii=False)}

This alert was generated by StockInfoDownloader Error Monitoring System.
            """
            
            msg.attach(MIMEText(body, 'plain', 'utf-8'))
            
            # 发送邮件
            with smtplib.SMTP(smtp_server, smtp_port) as server:
                server.starttls()
                server.login(username, password)
                server.send_message(msg)
            
            logger.info(f"邮件通知发送成功: {alert.id}")
            return True
            
        except Exception as e:
            logger.error(f"邮件通知发送失败: {e}")
            return False
    
    def test_connection(self) -> bool:
        """测试邮件服务器连接"""
        try:
            smtp_server = self.config['smtp_server']
            smtp_port = self.config['smtp_port']
            username = self.config['username']
            password = self.config['password']
            
            with smtplib.SMTP(smtp_server, smtp_port) as server:
                server.starttls()
                server.login(username, password)
            
            logger.info("邮件服务器连接测试成功")
            return True
            
        except Exception as e:
            logger.error(f"邮件服务器连接测试失败: {e}")
            return False

class WebhookNotificationChannel(NotificationChannel):
    """Webhook通知渠道"""
    
    def send_notification(self, alert: Alert) -> bool:
        """发送Webhook通知"""
        try:
            if not self.enabled:
                return False
            
            webhook_url = self.config['webhook_url']
            headers = self.config.get('headers', {'Content-Type': 'application/json'})
            timeout = self.config.get('timeout', 30)
            
            # 准备请求数据
            payload = {
                'alert_id': alert.id,
                'rule_name': alert.rule_name,
                'severity': alert.severity.value,
                'message': alert.message,
                'status': alert.status.value,
                'triggered_at': alert.triggered_at.isoformat(),
                'context': alert.context or {}
            }
            
            # 发送请求
            response = requests.post(
                webhook_url,
                json=payload,
                headers=headers,
                timeout=timeout
            )
            
            if response.status_code == 200:
                logger.info(f"Webhook通知发送成功: {alert.id}")
                return True
            else:
                logger.error(f"Webhook通知发送失败: HTTP {response.status_code}")
                return False
                
        except Exception as e:
            logger.error(f"Webhook通知发送失败: {e}")
            return False
    
    def test_connection(self) -> bool:
        """测试Webhook连接"""
        try:
            webhook_url = self.config['webhook_url']
            timeout = self.config.get('timeout', 30)
            
            # 发送测试请求
            test_payload = {'test': True, 'timestamp': datetime.now().isoformat()}
            response = requests.post(
                webhook_url,
                json=test_payload,
                timeout=timeout
            )
            
            if response.status_code == 200:
                logger.info("Webhook连接测试成功")
                return True
            else:
                logger.error(f"Webhook连接测试失败: HTTP {response.status_code}")
                return False
                
        except Exception as e:
            logger.error(f"Webhook连接测试失败: {e}")
            return False

class SlackNotificationChannel(NotificationChannel):
    """Slack通知渠道"""
    
    def send_notification(self, alert: Alert) -> bool:
        """发送Slack通知"""
        try:
            if not self.enabled:
                return False
            
            webhook_url = self.config['webhook_url']
            timeout = self.config.get('timeout', 30)
            
            # 准备Slack消息
            color_map = {
                AlertLevel.INFO: '#36a64f',      # 绿色
                AlertLevel.WARNING: '#ff9500',   # 橙色
                AlertLevel.ERROR: '#ff0000',     # 红色
                AlertLevel.CRITICAL: '#990000',   # 深红色
                AlertLevel.EMERGENCY: '#660000'  # 紫红色
            }
            
            payload = {
                'attachments': [
                    {
                        'color': color_map.get(alert.severity, '#ff0000'),
                        'title': f'StockInfoDownloader Alert: {alert.rule_name}',
                        'text': alert.message,
                        'fields': [
                            {
                                'title': 'Severity',
                                'value': alert.severity.value,
                                'short': True
                            },
                            {
                                'title': 'Status',
                                'value': alert.status.value,
                                'short': True
                            },
                            {
                                'title': 'Triggered At',
                                'value': alert.triggered_at.strftime('%Y-%m-%d %H:%M:%S'),
                                'short': False
                            }
                        ],
                        'footer': 'StockInfoDownloader Error Monitoring',
                        'ts': int(alert.triggered_at.timestamp())
                    }
                ]
            }
            
            # 发送请求
            response = requests.post(
                webhook_url,
                json=payload,
                timeout=timeout
            )
            
            if response.status_code == 200:
                logger.info(f"Slack通知发送成功: {alert.id}")
                return True
            else:
                logger.error(f"Slack通知发送失败: HTTP {response.status_code}")
                return False
                
        except Exception as e:
            logger.error(f"Slack通知发送失败: {e}")
            return False
    
    def test_connection(self) -> bool:
        """测试Slack连接"""
        try:
            webhook_url = self.config['webhook_url']
            timeout = self.config.get('timeout', 30)
            
            # 发送测试消息
            test_payload = {
                'text': 'StockInfoDownloader Alert System Test',
                'attachments': [
                    {
                        'color': '#36a64f',
                        'title': 'Test Alert',
                        'text': 'This is a test message from StockInfoDownloader',
                        'fields': [
                            {
                                'title': 'Test',
                                'value': 'Connection Test',
                                'short': True
                            }
                        ]
                    }
                ]
            }
            
            response = requests.post(
                webhook_url,
                json=test_payload,
                timeout=timeout
            )
            
            if response.status_code == 200:
                logger.info("Slack连接测试成功")
                return True
            else:
                logger.error(f"Slack连接测试失败: HTTP {response.status_code}")
                return False
                
        except Exception as e:
            logger.error(f"Slack连接测试失败: {e}")
            return False

class ErrorMonitoringSystem:
    """错误监控系统"""
    
    def __init__(self, config: Dict[str, Any]):
        """
        初始化错误监控系统
        
        Args:
            config: 监控系统配置
        """
        self.config = config
        self.alert_rules: List[AlertRule] = []
        self.active_alerts: Dict[str, Alert] = {}
        self.notification_channels: Dict[str, NotificationChannel] = {}
        self.alert_history: List[Alert] = []
        self.max_history_size = 1000
        
        # 初始化通知渠道
        self._initialize_notification_channels()
        
        # 加载默认告警规则
        self._load_default_rules()
        
        # 启动监控循环
        self.running = False
        self.monitor_thread = None
    
    def _initialize_notification_channels(self):
        """初始化通知渠道"""
        channels_config = self.config.get('notification_channels', {})
        
        for channel_name, channel_config in channels_config.items():
            channel_type = channel_config.get('type')
            
            if channel_type == 'email':
                self.notification_channels[channel_name] = EmailNotificationChannel(
                    channel_name, channel_config
                )
            elif channel_type == 'webhook':
                self.notification_channels[channel_name] = WebhookNotificationChannel(
                    channel_name, channel_config
                )
            elif channel_type == 'slack':
                self.notification_channels[channel_name] = SlackNotificationChannel(
                    channel_name, channel_config
                )
            else:
                logger.warning(f"未知的通知渠道类型: {channel_type}")
    
    def _load_default_rules(self):
        """加载默认告警规则"""
        default_rules = [
            AlertRule(
                name="high_error_rate",
                description="高错误率告警",
                condition="error_rate > threshold",
                threshold=0.1,  # 10%
                time_window=5,   # 5分钟
                severity=AlertLevel.WARNING,
                notification_channels=['log', 'email']
            ),
            AlertRule(
                name="critical_error_count",
                description="严重错误数量告警",
                condition="critical_error_count > threshold",
                threshold=5,
                time_window=10,
                severity=AlertLevel.ERROR,
                notification_channels=['log', 'email', 'slack']
            ),
            AlertRule(
                name="recovery_failure",
                description="错误恢复失败告警",
                condition="recovery_failure_rate > threshold",
                threshold=0.5,  # 50%
                time_window=15,
                severity=AlertLevel.CRITICAL,
                notification_channels=['log', 'email', 'slack']
            ),
            AlertRule(
                name="system_unavailable",
                description="系统不可用告警",
                condition="system_unavailable",
                threshold=1,
                time_window=1,
                severity=AlertLevel.EMERGENCY,
                notification_channels=['log', 'email', 'slack']
            )
        ]
        
        for rule in default_rules:
            self.add_alert_rule(rule)
    
    def add_alert_rule(self, rule: AlertRule):
        """添加告警规则"""
        self.alert_rules.append(rule)
        logger.info(f"添加告警规则: {rule.name}")
    
    def remove_alert_rule(self, rule_name: str):
        """移除告警规则"""
        self.alert_rules = [rule for rule in self.alert_rules if rule.name != rule_name]
        logger.info(f"移除告警规则: {rule_name}")
    
    def start_monitoring(self):
        """启动监控"""
        if self.running:
            logger.warning("监控系统已在运行中")
            return
        
        self.running = True
        logger.info("启动错误监控系统")
        
        # 启动监控线程
        import threading
        self.monitor_thread = threading.Thread(target=self._monitoring_loop, daemon=True)
        self.monitor_thread.start()
    
    def stop_monitoring(self):
        """停止监控"""
        self.running = False
        if self.monitor_thread:
            self.monitor_thread.join(timeout=5)
        logger.info("停止错误监控系统")
    
    def _monitoring_loop(self):
        """监控循环"""
        while self.running:
            try:
                # 检查所有告警规则
                for rule in self.alert_rules:
                    if rule.enabled:
                        self._check_alert_rule(rule)
                
                # 清理已解决的告警
                self._cleanup_resolved_alerts()
                
                # 等待下次检查
                time.sleep(60)  # 每分钟检查一次
                
            except Exception as e:
                logger.error(f"监控循环出错: {e}")
                time.sleep(60)
    
    def _check_alert_rule(self, rule: AlertRule):
        """检查告警规则"""
        try:
            # 获取错误统计信息
            error_stats = error_logger.get_error_summary(hours=rule.time_window // 60)
            
            # 检查冷却期
            if rule.name in self.active_alerts:
                active_alert = self.active_alerts[rule.name]
                if (datetime.now() - active_alert.triggered_at).total_seconds() < rule.cooldown_period * 60:
                    return  # 在冷却期内，不重复触发
            
            # 评估规则条件
            should_alert = self._evaluate_rule_condition(rule, error_stats)
            
            if should_alert:
                self._trigger_alert(rule, error_stats)
                
        except Exception as e:
            logger.error(f"检查告警规则失败 {rule.name}: {e}")
    
    def _evaluate_rule_condition(self, rule: AlertRule, stats: Dict[str, Any]) -> bool:
        """评估规则条件"""
        try:
            if rule.condition == "error_rate > threshold":
                error_rate = stats.get('error_frequency', 0)
                return error_rate > rule.threshold
            
            elif rule.condition == "critical_error_count > threshold":
                critical_count = stats.get('severities', {}).get('CRITICAL', 0)
                return critical_count > rule.threshold
            
            elif rule.condition == "recovery_failure_rate > threshold":
                recovery_rate = stats.get('recovery_rate', 1.0)
                failure_rate = 1.0 - recovery_rate
                return failure_rate > rule.threshold
            
            elif rule.condition == "system_unavailable":
                # 检查系统是否可用
                total_errors = stats.get('total_errors', 0)
                return total_errors > rule.threshold
            
            return False
            
        except Exception as e:
            logger.error(f"评估规则条件失败 {rule.name}: {e}")
            return False
    
    def _trigger_alert(self, rule: AlertRule, context: Dict[str, Any]):
        """触发告警"""
        try:
            # 创建告警
            alert = Alert(
                id=f"{rule.name}_{int(time.time())}",
                rule_name=rule.name,
                message=f"告警规则 {rule.name} 被触发",
                severity=rule.severity,
                status=AlertStatus.ACTIVE,
                triggered_at=datetime.now(),
                context=context
            )
            
            # 存储告警
            self.active_alerts[rule.name] = alert
            self.alert_history.append(alert)
            
            # 限制历史记录大小
            if len(self.alert_history) > self.max_history_size:
                self.alert_history = self.alert_history[-self.max_history_size:]
            
            # 发送通知
            self._send_alert_notifications(alert)
            
            logger.warning(f"触发告警: {rule.name} - {alert.message}")
            
        except Exception as e:
            logger.error(f"触发告警失败 {rule.name}: {e}")
    
    def _send_alert_notifications(self, alert: Alert):
        """发送告警通知"""
        try:
            for channel_name in alert.rule.notification_channels:
                if channel_name in self.notification_channels:
                    channel = self.notification_channels[channel_name]
                    
                    if channel.send_notification(alert):
                        alert.notification_sent = True
                        logger.info(f"告警通知发送成功: {alert.id} -> {channel_name}")
                    else:
                        logger.error(f"告警通知发送失败: {alert.id} -> {channel_name}")
                else:
                    logger.warning(f"未找到通知渠道: {channel_name}")
                    
        except Exception as e:
            logger.error(f"发送告警通知失败: {e}")
    
    def _cleanup_resolved_alerts(self):
        """清理已解决的告警"""
        try:
            resolved_alerts = []
            
            for alert_id, alert in self.active_alerts.items():
                # 检查告警是否应该被标记为已解决
                if self._should_resolve_alert(alert):
                    alert.status = AlertStatus.RESOLVED
                    alert.resolved_at = datetime.now()
                    resolved_alerts.append(alert_id)
                    
                    logger.info(f"告警已解决: {alert.rule_name}")
            
            # 从活动告警中移除已解决的告警
            for alert_id in resolved_alerts:
                del self.active_alerts[alert_id]
                
        except Exception as e:
            logger.error(f"清理已解决告警失败: {e}")
    
    def _should_resolve_alert(self, alert: Alert) -> bool:
        """判断告警是否应该被解决"""
        try:
            # 获取最新的错误统计
            recent_stats = error_logger.get_error_summary(hours=1)
            
            # 根据告警类型判断是否应该解决
            if alert.rule_name == "high_error_rate":
                error_rate = recent_stats.get('error_frequency', 0)
                return error_rate < 0.05  # 错误率低于5%
            
            elif alert.rule_name == "critical_error_count":
                critical_count = recent_stats.get('severities', {}).get('CRITICAL', 0)
                return critical_count == 0  # 没有严重错误
            
            elif alert.rule_name == "recovery_failure":
                recovery_rate = recent_stats.get('recovery_rate', 1.0)
                return recovery_rate > 0.8  # 恢复率高于80%
            
            elif alert.rule_name == "system_unavailable":
                total_errors = recent_stats.get('total_errors', 0)
                return total_errors == 0  # 没有错误
            
            return False
            
        except Exception as e:
            logger.error(f"判断告警解决状态失败: {e}")
            return False
    
    def acknowledge_alert(self, alert_id: str) -> bool:
        """确认告警"""
        try:
            for alert in self.active_alerts.values():
                if alert.id == alert_id:
                    alert.status = AlertStatus.ACKNOWLEDGED
                    alert.acknowledged_at = datetime.now()
                    logger.info(f"告警已确认: {alert_id}")
                    return True
            
            return False
            
        except Exception as e:
            logger.error(f"确认告警失败: {e}")
            return False
    
    def get_alert_status(self) -> Dict[str, Any]:
        """获取告警状态"""
        try:
            return {
                'active_alerts': len(self.active_alerts),
                'total_alerts': len(self.alert_history),
                'alerts_by_severity': self._get_alerts_by_severity(),
                'recent_alerts': [
                    alert.to_dict() for alert in self.alert_history[-10:]
                ],
                'notification_channels': {
                    name: {
                        'enabled': channel.enabled,
                        'type': type(channel).__name__
                    }
                    for name, channel in self.notification_channels.items()
                }
            }
            
        except Exception as e:
            logger.error(f"获取告警状态失败: {e}")
            return {'error': str(e)}
    
    def _get_alerts_by_severity(self) -> Dict[str, int]:
        """按严重级别统计告警"""
        severity_count = {}
        
        for alert in self.active_alerts.values():
            severity = alert.severity.value
            severity_count[severity] = severity_count.get(severity, 0) + 1
        
        return severity_count
    
    def test_notification_channels(self) -> Dict[str, bool]:
        """测试所有通知渠道"""
        results = {}
        
        for name, channel in self.notification_channels.items():
            try:
                results[name] = channel.test_connection()
            except Exception as e:
                logger.error(f"测试通知渠道失败 {name}: {e}")
                results[name] = False
        
        return results
    
    def export_alert_report(self, output_path: str, days: int = 7) -> bool:
        """导出告警报告"""
        try:
            cutoff_time = datetime.now() - timedelta(days=days)
            recent_alerts = [
                alert for alert in self.alert_history
                if alert.triggered_at >= cutoff_time
            ]
            
            report_data = {
                'generated_at': datetime.now().isoformat(),
                'period_days': days,
                'total_alerts': len(recent_alerts),
                'alerts_by_severity': self._get_alerts_by_severity(),
                'alerts': [alert.to_dict() for alert in recent_alerts]
            }
            
            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump(report_data, f, ensure_ascii=False, indent=2)
            
            logger.info(f"告警报告已导出到: {output_path}")
            return True
            
        except Exception as e:
            logger.error(f"导出告警报告失败: {e}")
            return False

# 全局监控系统实例
_monitoring_system = None

def get_monitoring_system(config: Dict[str, Any] = None) -> ErrorMonitoringSystem:
    """获取全局监控系统实例"""
    global _monitoring_system
    
    if _monitoring_system is None:
        if config is None:
            config = {
                'notification_channels': {
                    'log': {
                        'type': 'log',
                        'enabled': True
                    }
                }
            }
        
        _monitoring_system = ErrorMonitoringSystem(config)
    
    return _monitoring_system

def start_monitoring(config: Dict[str, Any] = None):
    """启动错误监控"""
    system = get_monitoring_system(config)
    system.start_monitoring()

def stop_monitoring():
    """停止错误监控"""
    global _monitoring_system
    if _monitoring_system:
        _monitoring_system.stop_monitoring()

def get_alert_status() -> Dict[str, Any]:
    """获取告警状态"""
    global _monitoring_system
    if _monitoring_system:
        return _monitoring_system.get_alert_status()
    return {'error': 'Monitoring system not initialized'}

def acknowledge_alert(alert_id: str) -> bool:
    """确认告警"""
    global _monitoring_system
    if _monitoring_system:
        return _monitoring_system.acknowledge_alert(alert_id)
    return False