"""
Error Monitoring and Alert System
Provides real-time error monitoring, alert triggering, and notification functionality
"""

import json
import smtplib
import time
from dataclasses import asdict, dataclass
from datetime import datetime, timedelta
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from enum import Enum
from typing import Any, Dict, List, Optional, Union

import requests

from .error_logger import error_logger
from .logger import get_logger

logger = get_logger(__name__)


# Alert level enum
class AlertLevel(Enum):
    """Alert level"""

    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"
    EMERGENCY = "EMERGENCY"


# Alert status enum
class AlertStatus(Enum):
    """Alert status"""

    ACTIVE = "ACTIVE"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"
    SUPPRESSED = "SUPPRESSED"


@dataclass
class AlertRule:
    """Alert rule"""

    name: str
    description: str
    condition: str  # Condition expression
    threshold: Union[int, float]
    time_window: int  # Time window (minutes)
    severity: AlertLevel
    enabled: bool = True
    cooldown_period: int = 60  # Cooldown period (minutes)
    notification_channels: List[str] = None

    def __post_init__(self):
        if self.notification_channels is None:
            self.notification_channels = ["log"]


@dataclass
class Alert:
    """Alert information"""

    id: str
    rule_name: str
    message: str
    severity: AlertLevel
    status: AlertStatus
    triggered_at: datetime
    acknowledged_at: Optional[datetime] = None
    resolved_at: Optional[datetime] = None
    context: Dict[str, Any] = None
    notification_sent: bool = False

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        data = asdict(self)
        data["triggered_at"] = self.triggered_at.isoformat()
        if self.acknowledged_at:
            data["acknowledged_at"] = self.acknowledged_at.isoformat()
        if self.resolved_at:
            data["resolved_at"] = self.resolved_at.isoformat()
        data["severity"] = self.severity.value
        data["status"] = self.status.value
        return data


class NotificationChannel:
    """Notification channel base class"""

    def __init__(self, name: str, config: Dict[str, Any]):
        self.name = name
        self.config = config
        self.enabled = config.get("enabled", True)

    def send_notification(self, alert: Alert) -> bool:
        """Send notification"""
        raise NotImplementedError

    def test_connection(self) -> bool:
        """Test connection"""
        raise NotImplementedError


class EmailNotificationChannel(NotificationChannel):
    """Email notification channel"""

    def send_notification(self, alert: Alert) -> bool:
        """Send email notification"""
        try:
            if not self.enabled:
                return False

            smtp_server = self.config["smtp_server"]
            smtp_port = self.config["smtp_port"]
            username = self.config["username"]
            password = self.config["password"]
            from_addr = self.config["from_address"]
            to_addrs = self.config["to_addresses"]

            # Create email
            msg = MIMEMultipart()
            msg["From"] = from_addr
            msg["To"] = ", ".join(to_addrs)
            msg["Subject"] = (
                f"[{alert.severity.value}] StockInfoDownloader Alert: {alert.rule_name}"
            )

            # Email content
            body = f"""
Alert Details:
- Rule: {alert.rule_name}
- Severity: {alert.severity.value}
- Message: {alert.message}
- Triggered At: {alert.triggered_at.strftime('%Y-%m-%d %H:%M:%S')}
- Status: {alert.status.value}

Context:
{json.dumps(alert.context or {}, indent=2, ensure_ascii=False)}

This alert was generated by StockInfoDownloader Error Monitoring System.
            """

            msg.attach(MIMEText(body, "plain", "utf-8"))

            # Send email
            with smtplib.SMTP(smtp_server, smtp_port) as server:
                server.starttls()
                server.login(username, password)
                server.send_message(msg)

            logger.info(f"Email notification sent successfully: {alert.id}")
            return True

        except Exception as e:
            logger.error(f"Email notification failed: {e}")
            return False

    def test_connection(self) -> bool:
        """Test email server connection"""
        try:
            smtp_server = self.config["smtp_server"]
            smtp_port = self.config["smtp_port"]
            username = self.config["username"]
            password = self.config["password"]

            with smtplib.SMTP(smtp_server, smtp_port) as server:
                server.starttls()
                server.login(username, password)

            logger.info("Email server connection test successful")
            return True

        except Exception as e:
            logger.error(f"Email server connection test failed: {e}")
            return False


class WebhookNotificationChannel(NotificationChannel):
    """Webhook notification channel"""

    def send_notification(self, alert: Alert) -> bool:
        """Send Webhook notification"""
        try:
            if not self.enabled:
                return False

            webhook_url = self.config["webhook_url"]
            headers = self.config.get("headers", {"Content-Type": "application/json"})
            timeout = self.config.get("timeout", 30)

            # Prepare request data
            payload = {
                "alert_id": alert.id,
                "rule_name": alert.rule_name,
                "severity": alert.severity.value,
                "message": alert.message,
                "status": alert.status.value,
                "triggered_at": alert.triggered_at.isoformat(),
                "context": alert.context or {},
            }

            # Send request
            response = requests.post(
                webhook_url, json=payload, headers=headers, timeout=timeout
            )

            if response.status_code == 200:
                logger.info(f"Webhook notification sent successfully: {alert.id}")
                return True
            else:
                logger.error(f"Webhook notification failed: HTTP {response.status_code}")
                return False

        except Exception as e:
            logger.error(f"Webhook notification failed: {e}")
            return False

    def test_connection(self) -> bool:
        """Test Webhook connection"""
        try:
            webhook_url = self.config["webhook_url"]
            timeout = self.config.get("timeout", 30)

            # Send test request
            test_payload = {"test": True, "timestamp": datetime.now().isoformat()}
            response = requests.post(webhook_url, json=test_payload, timeout=timeout)

            if response.status_code == 200:
                logger.info("Webhook connection test successful")
                return True
            else:
                logger.error(f"Webhook connection test failed: HTTP {response.status_code}")
                return False

        except Exception as e:
            logger.error(f"Webhook connection test failed: {e}")
            return False


class SlackNotificationChannel(NotificationChannel):
    """Slack notification channel"""

    def send_notification(self, alert: Alert) -> bool:
        """Send Slack notification"""
        try:
            if not self.enabled:
                return False

            webhook_url = self.config["webhook_url"]
            timeout = self.config.get("timeout", 30)

            # Prepare Slack message
            color_map = {
                AlertLevel.INFO: "#36a64f",  # Green
                AlertLevel.WARNING: "#ff9500",  # Orange
                AlertLevel.ERROR: "#ff0000",  # Red
                AlertLevel.CRITICAL: "#990000",  # Dark red
                AlertLevel.EMERGENCY: "#660000",  # Purple red
            }

            payload = {
                "attachments": [
                    {
                        "color": color_map.get(alert.severity, "#ff0000"),
                        "title": f"StockInfoDownloader Alert: {alert.rule_name}",
                        "text": alert.message,
                        "fields": [
                            {
                                "title": "Severity",
                                "value": alert.severity.value,
                                "short": True,
                            },
                            {
                                "title": "Status",
                                "value": alert.status.value,
                                "short": True,
                            },
                            {
                                "title": "Triggered At",
                                "value": alert.triggered_at.strftime(
                                    "%Y-%m-%d %H:%M:%S"
                                ),
                                "short": False,
                            },
                        ],
                        "footer": "StockInfoDownloader Error Monitoring",
                        "ts": int(alert.triggered_at.timestamp()),
                    }
                ]
            }

            # Send request
            response = requests.post(webhook_url, json=payload, timeout=timeout)

            if response.status_code == 200:
                logger.info(f"Slack notification sent successfully: {alert.id}")
                return True
            else:
                logger.error(f"Slack notification failed: HTTP {response.status_code}")
                return False

        except Exception as e:
            logger.error(f"Slack notification failed: {e}")
            return False

    def test_connection(self) -> bool:
        """Test Slack connection"""
        try:
            webhook_url = self.config["webhook_url"]
            timeout = self.config.get("timeout", 30)

            # Send test message
            test_payload = {
                "text": "StockInfoDownloader Alert System Test",
                "attachments": [
                    {
                        "color": "#36a64f",
                        "title": "Test Alert",
                        "text": "This is a test message from StockInfoDownloader",
                        "fields": [
                            {"title": "Test", "value": "Connection Test", "short": True}
                        ],
                    }
                ],
            }

            response = requests.post(webhook_url, json=test_payload, timeout=timeout)

            if response.status_code == 200:
                logger.info("Slack connection test successful")
                return True
            else:
                logger.error(f"Slack connection test failed: HTTP {response.status_code}")
                return False

        except Exception as e:
            logger.error(f"Slack connection test failed: {e}")
            return False


class ErrorMonitoringSystem:
    """Error monitoring system"""

    def __init__(self, config: Dict[str, Any]):
        """
        Initialize error monitoring system

        Args:
            config: Monitoring system configuration
        """
        self.config = config
        self.alert_rules: List[AlertRule] = []
        self.active_alerts: Dict[str, Alert] = {}
        self.notification_channels: Dict[str, NotificationChannel] = {}
        self.alert_history: List[Alert] = []
        self.max_history_size = 1000

        # Initialize notification channels
        self._initialize_notification_channels()

        # Load default alert rules
        self._load_default_rules()

        # Start monitoring loop
        self.running = False
        self.monitor_thread = None

    def _initialize_notification_channels(self):
        """Initialize notification channels"""
        channels_config = self.config.get("notification_channels", {})

        for channel_name, channel_config in channels_config.items():
            channel_type = channel_config.get("type")

            if channel_type == "email":
                self.notification_channels[channel_name] = EmailNotificationChannel(
                    channel_name, channel_config
                )
            elif channel_type == "webhook":
                self.notification_channels[channel_name] = WebhookNotificationChannel(
                    channel_name, channel_config
                )
            elif channel_type == "slack":
                self.notification_channels[channel_name] = SlackNotificationChannel(
                    channel_name, channel_config
                )
            else:
                logger.warning(f"Unknown notification channel type: {channel_type}")

    def _load_default_rules(self):
        """Load default alert rules"""
        default_rules = [
            AlertRule(
                name="high_error_rate",
                description="High error rate alert",
                condition="error_rate > threshold",
                threshold=0.1,  # 10%
                time_window=5,  # 5 minutes
                severity=AlertLevel.WARNING,
                notification_channels=["log", "email"],
            ),
            AlertRule(
                name="critical_error_count",
                description="Critical error count alert",
                condition="critical_error_count > threshold",
                threshold=5,
                time_window=10,
                severity=AlertLevel.ERROR,
                notification_channels=["log", "email", "slack"],
            ),
            AlertRule(
                name="recovery_failure",
                description="Error recovery failure alert",
                condition="recovery_failure_rate > threshold",
                threshold=0.5,  # 50%
                time_window=15,
                severity=AlertLevel.CRITICAL,
                notification_channels=["log", "email", "slack"],
            ),
            AlertRule(
                name="system_unavailable",
                description="System unavailable alert",
                condition="system_unavailable",
                threshold=1,
                time_window=1,
                severity=AlertLevel.EMERGENCY,
                notification_channels=["log", "email", "slack"],
            ),
        ]

        for rule in default_rules:
            self.add_alert_rule(rule)

    def add_alert_rule(self, rule: AlertRule):
        """Add alert rule"""
        self.alert_rules.append(rule)
        logger.info(f"Alert rule added: {rule.name}")

    def remove_alert_rule(self, rule_name: str):
        """Remove alert rule"""
        self.alert_rules = [rule for rule in self.alert_rules if rule.name != rule_name]
        logger.info(f"Alert rule removed: {rule_name}")

    def start_monitoring(self):
        """Start monitoring"""
        if self.running:
            logger.warning("Monitoring system is already running")
            return

        self.running = True
        logger.info("Starting error monitoring system")

        # Start monitoring thread
        import threading

        self.monitor_thread = threading.Thread(
            target=self._monitoring_loop, daemon=True
        )
        self.monitor_thread.start()

    def stop_monitoring(self):
        """Stop monitoring"""
        self.running = False
        if self.monitor_thread:
            self.monitor_thread.join(timeout=5)
        logger.info("Stopping error monitoring system")

    def _monitoring_loop(self):
        """Monitoring loop"""
        while self.running:
            try:
                # Check all alert rules
                for rule in self.alert_rules:
                    if rule.enabled:
                        self._check_alert_rule(rule)

                # Clean up resolved alerts
                self._cleanup_resolved_alerts()

                # Wait for next check
                time.sleep(60)  # Check every minute

            except Exception as e:
                logger.error(f"Monitoring loop error: {e}")
                time.sleep(60)

    def _check_alert_rule(self, rule: AlertRule):
        """Check alert rule"""
        try:
            # Get error statistics
            error_stats = error_logger.get_error_summary(hours=rule.time_window // 60)

            # Check cooldown period
            if rule.name in self.active_alerts:
                active_alert = self.active_alerts[rule.name]
                if (
                    datetime.now() - active_alert.triggered_at
                ).total_seconds() < rule.cooldown_period * 60:
                    return  # In cooldown period, do not trigger again

            # Evaluate rule condition
            should_alert = self._evaluate_rule_condition(rule, error_stats)

            if should_alert:
                self._trigger_alert(rule, error_stats)

        except Exception as e:
            logger.error(f"Failed to check alert rule {rule.name}: {e}")

    def _evaluate_rule_condition(self, rule: AlertRule, stats: Dict[str, Any]) -> bool:
        """Evaluate rule condition"""
        try:
            if rule.condition == "error_rate > threshold":
                error_rate = stats.get("error_frequency", 0)
                return error_rate > rule.threshold

            elif rule.condition == "critical_error_count > threshold":
                critical_count = stats.get("severities", {}).get("CRITICAL", 0)
                return critical_count > rule.threshold

            elif rule.condition == "recovery_failure_rate > threshold":
                recovery_rate = stats.get("recovery_rate", 1.0)
                failure_rate = 1.0 - recovery_rate
                return failure_rate > rule.threshold

            elif rule.condition == "system_unavailable":
                # Check if system is available
                total_errors = stats.get("total_errors", 0)
                return total_errors > rule.threshold

            return False

        except Exception as e:
            logger.error(f"Failed to evaluate rule condition {rule.name}: {e}")
            return False

    def _trigger_alert(self, rule: AlertRule, context: Dict[str, Any]):
        """Trigger alert"""
        try:
            # Create alert
            alert = Alert(
                id=f"{rule.name}_{int(time.time())}",
                rule_name=rule.name,
                message=f"Alert rule {rule.name} triggered",
                severity=rule.severity,
                status=AlertStatus.ACTIVE,
                triggered_at=datetime.now(),
                context=context,
            )

            # Store alert
            self.active_alerts[rule.name] = alert
            self.alert_history.append(alert)

            # Limit history size
            if len(self.alert_history) > self.max_history_size:
                self.alert_history = self.alert_history[-self.max_history_size :]

            # Send notifications
            self._send_alert_notifications(alert)

            logger.warning(f"Alert triggered: {rule.name} - {alert.message}")

        except Exception as e:
            logger.error(f"Failed to trigger alert {rule.name}: {e}")

    def _send_alert_notifications(self, alert: Alert):
        """Send alert notification"""
        try:
            for channel_name in alert.rule.notification_channels:
                if channel_name in self.notification_channels:
                    channel = self.notification_channels[channel_name]

                    if channel.send_notification(alert):
                        alert.notification_sent = True
                        logger.info(f"Alert notification sent successfully: {alert.id} -> {channel_name}")
                    else:
                        logger.error(f"Alert notification failed: {alert.id} -> {channel_name}")
                else:
                    logger.warning(f"Notification channel not found: {channel_name}")

        except Exception as e:
            logger.error(f"Failed to send alert notification: {e}")

    def _cleanup_resolved_alerts(self):
        """Clean up resolved alerts"""
        try:
            resolved_alerts = []

            for alert_id, alert in self.active_alerts.items():
                # Check if alert should be marked as resolved
                if self._should_resolve_alert(alert):
                    alert.status = AlertStatus.RESOLVED
                    alert.resolved_at = datetime.now()
                    resolved_alerts.append(alert_id)

                    logger.info(f"Alert resolved: {alert.rule_name}")

            # Remove resolved alerts from active alerts
            for alert_id in resolved_alerts:
                del self.active_alerts[alert_id]

        except Exception as e:
            logger.error(f"Failed to clean up resolved alerts: {e}")

    def _should_resolve_alert(self, alert: Alert) -> bool:
        """Determine if alert should be resolved"""
        try:
            # Get latest error stats
            recent_stats = error_logger.get_error_summary(hours=1)

            # Determine if should resolve based on alert type
            if alert.rule_name == "high_error_rate":
                error_rate = recent_stats.get("error_frequency", 0)
                return error_rate < 0.05  # Error rate below 5%

            elif alert.rule_name == "critical_error_count":
                critical_count = recent_stats.get("severities", {}).get("CRITICAL", 0)
                return critical_count == 0  # No critical errors

            elif alert.rule_name == "recovery_failure":
                recovery_rate = recent_stats.get("recovery_rate", 1.0)
                return recovery_rate > 0.8  # Recovery rate above 80%

            elif alert.rule_name == "system_unavailable":
                total_errors = recent_stats.get("total_errors", 0)
                return total_errors == 0  # No errors

            return False

        except Exception as e:
            logger.error(f"Failed to determine alert resolution status: {e}")
            return False

    def acknowledge_alert(self, alert_id: str) -> bool:
        """Acknowledge alert"""
        try:
            for alert in self.active_alerts.values():
                if alert.id == alert_id:
                    alert.status = AlertStatus.ACKNOWLEDGED
                    alert.acknowledged_at = datetime.now()
                    logger.info(f"Alert acknowledged: {alert_id}")
                    return True

            return False

        except Exception as e:
            logger.error(f"Failed to acknowledge alert: {e}")
            return False

    def get_alert_status(self) -> Dict[str, Any]:
        """Get alert status"""
        try:
            return {
                "active_alerts": len(self.active_alerts),
                "total_alerts": len(self.alert_history),
                "alerts_by_severity": self._get_alerts_by_severity(),
                "recent_alerts": [
                    alert.to_dict() for alert in self.alert_history[-10:]
                ],
                "notification_channels": {
                    name: {"enabled": channel.enabled, "type": type(channel).__name__}
                    for name, channel in self.notification_channels.items()
                },
            }

        except Exception as e:
            logger.error(f"Failed to get alert status: {e}")
            return {"error": str(e)}

    def _get_alerts_by_severity(self) -> Dict[str, int]:
        """Count alerts by severity level"""
        severity_count = {}

        for alert in self.active_alerts.values():
            severity = alert.severity.value
            severity_count[severity] = severity_count.get(severity, 0) + 1

        return severity_count

    def test_notification_channels(self) -> Dict[str, bool]:
        """Test all notification channels"""
        results = {}

        for name, channel in self.notification_channels.items():
            try:
                results[name] = channel.test_connection()
            except Exception as e:
                logger.error(f"Failed to test notification channel {name}: {e}")
                results[name] = False

        return results

    def export_alert_report(self, output_path: str, days: int = 7) -> bool:
        """Export alert report"""
        try:
            cutoff_time = datetime.now() - timedelta(days=days)
            recent_alerts = [
                alert
                for alert in self.alert_history
                if alert.triggered_at >= cutoff_time
            ]

            report_data = {
                "generated_at": datetime.now().isoformat(),
                "period_days": days,
                "total_alerts": len(recent_alerts),
                "alerts_by_severity": self._get_alerts_by_severity(),
                "alerts": [alert.to_dict() for alert in recent_alerts],
            }

            with open(output_path, "w", encoding="utf-8") as f:
                json.dump(report_data, f, ensure_ascii=False, indent=2)

            logger.info(f"Alert report exported to: {output_path}")
            return True

        except Exception as e:
            logger.error(f"Failed to export alert report: {e}")
            return False


# Global monitoring system instance
_monitoring_system = None


def get_monitoring_system(config: Dict[str, Any] = None) -> ErrorMonitoringSystem:
    """Get global monitoring system instance"""
    global _monitoring_system

    if _monitoring_system is None:
        if config is None:
            config = {
                "notification_channels": {"log": {"type": "log", "enabled": True}}
            }

        _monitoring_system = ErrorMonitoringSystem(config)

    return _monitoring_system


def start_monitoring(config: Dict[str, Any] = None):
    """Start error monitoring"""
    system = get_monitoring_system(config)
    system.start_monitoring()


def stop_monitoring():
    """Stop error monitoring"""
    global _monitoring_system
    if _monitoring_system:
        _monitoring_system.stop_monitoring()


def get_alert_status() -> Dict[str, Any]:
    """Get alert status"""
    global _monitoring_system
    if _monitoring_system:
        return _monitoring_system.get_alert_status()
    return {"error": "Monitoring system not initialized"}


def acknowledge_alert(alert_id: str) -> bool:
    """Acknowledge alert"""
    global _monitoring_system
    if _monitoring_system:
        return _monitoring_system.acknowledge_alert(alert_id)
    return False
